import datetime
import pyttsx3 #it converts the text into speech
import speech_recognition as sr #it used to listen the spoken words and identify them
import webbrowser #allows displaying Web-based documents to users
import time
from pip import __main__
import os
import subprocess
def sptext():
    while True:
        recog = sr.Recognizer()
        with sr.Microphone() as source:
            print("Listening...")
            recog.adjust_for_ambient_noise(source)
            audio = recog.listen(source)
            try:
                print("Recognizing...")
                data = recog.recognize_google(audio)
                return data
            except sr.UnknownValueError:
                print("Not Uderstanding...!!!")

def textsp(x): #This function used to create speech on the text generated by machine based on the user's speech
    engine = pyttsx3.init() #This variable calls the class "init()" from pyttsx3 which is used to convert the text into speech
    voices = engine.getProperty('voices') #This variable get the voice_property as 'getProperty()' from "engine"
    engine.setProperty('voice',voices[0].id) #Here the setProperty use to set voice as male(voices[0].id) and for female(voices[1].id) from "engine"
    speed_rate = engine.getProperty('rate')
    engine.setProperty('rate',140)#Here the 'setproperty' use to set speed rate of the speech
    engine.say(x)   #it will speech out the text
    engine.runAndWait() #used to start the speech synthesis engine and block the application until the engine has finished speaking...

if (__name__ == '__main__'): #This is the main function that will be used to perform the whole operation
    if "hey peter" in sptext().lower():
        print("Hello")
        textsp("Hello")
        print("Please give your identity to access...")
        textsp("Please give your identity to access...")
        if "2003" in sptext().lower():
            print("Access Granted...")
            textsp("Access Granted")
            print("Hello Sir, How can I help you?")
            textsp("Hello Sir how can i help you")
            while True:
                data1 = sptext().lower()
                if "old are you" in data1:
                    age = "I am two years old"
                    print(age)
                    textsp(age)
                elif "time" in data1:
                    time1 = datetime.datetime.now().strftime("Time: %I:%M:%p") #%I gives hours, %M gives minutes, %p gives AM or PM
                    print(time1)
                    textsp(time1)
                elif "youtube" in data1:
                    textsp("Opening Youtube...")
                    print("Opening Youtube...")
                    webbrowser.open("https://www.youtube.com/")  #In webbrowser module "open" function will open youtube with the given link
                elif "play song" in data1:
                    add = "E:\Music"
                    songlist = os.listdir(add)
                    print(songlist)
                    os.startfile(os.path.join(add,songlist[0]))
                elif "exit" in data1:
                    print("Thank You...")
                    textsp("Thank you")
                    break
                time.sleep(4)
        else:
            print("Access Denied!!!")
            textsp("Access Denied!!!")
    else:
        print("Sorry!!!")
        textsp("sorry")



